<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WhoWants20K_App\WhoWants20K_Application.csproj" />
    <ProjectReference Include="..\WhoWants20K_Domain\WhoWants20K_Domain.csproj" />
  </ItemGroup>

</Project>
